     

[build]
command = "npm run build"  # Adjust this based on your build command
publish = "dist"  # Adjust this based on your output directory

[dev]
command = "npm run start"  # Adjust this based on your development server command
