
[build]
  command = "npm run build"  # Update with your actual build command
  publish = "./views"        # Update based on your project structure

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
